In [1]:
def my_func1(x):
    return x**2

def numerical_derivative(f, x):
    delta_x = 1e-4
    return (f(x+delta_x)-f(x-delta_x))/(2*delta_x)

result = numerical_derivative(my_func1, 3)
print("result ==", result)

result == 6.000000000012662


In [3]:
import numpy as np

def my_func2(x):
    return 3*x*(np.exp(x))

def numerical_derivative(f, x):
    delta_x = 1e-4
    return (f(x+delta_x)-f(x-delta_x))/(2*delta_x)

result = numerical_derivative(my_func2, 2)
print("result ==", result)

print("3*ex(2) + 3*2*exp(2) == ", end='')
print(3*np.exp(2) + 3*2*np.exp(2))

result == 66.50150507518049
3*ex(2) + 3*2*exp(2) == 66.50150489037586


In [8]:
import numpy as np

def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    print("debug 1. initial input variable =", x)
    print("debug 2. initial grad =", grad)
    print("=======================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
    
        print("debug 3. idx = ", idx, ", x [idx] = ", x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug 4. grad[idx] = ", grad[idx])
        print("debug 5. grad = ", grad)
        print("=======================================")
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

# 입력변수 1개인 함수 f(x) = x**2
def func1(input_obj):
    x = input_obj[0]
    return x**2

# x = 3.0에서의 편미분 값
numerical_derivative(func1, np.array([3.0]))

debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx =  (0,) , x [idx] =  3.0
debug 4. grad[idx] =  6.000000000012662
debug 5. grad =  [6.]


array([6.])

In [11]:
import numpy as np

def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. initial input variable =", x)
    print("debug 2. initial grad =", grad)
    print("=======================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ", x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug 4. grad[idx] = ", grad[idx])
        print("debug 5. grad = ", grad)
        print("=======================================")
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

def func1(input_obj):
    
    x = input_obj[0]
    y = input_obj[1]
    
    return (2*x + 3*x*y + np.power(y,3))

input =  np.array([1.0, 2.0])
numerical_derivative(func1, input)

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
debug 4. grad[idx] =  7.999999999990237
debug 5. grad =  [8. 0.]
debug 3. idx =  (1,) , x[idx] =  2.0
debug 4. grad[idx] =  15.000000010019221
debug 5. grad =  [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [12]:
import numpy as np

def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. initial input variable =", x)
    print("debug 2. initial grad =", grad)
    print("=======================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ", x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*(delta_x))
        
        print("debug 4. grad[idx] = ", grad[idx])
        print("debug 5. grad = ", grad)
        print("=======================================")
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

def func1(input_obj):
    w = input_obj[0, 0]
    x = input_obj[0, 1]
    y = input_obj[1, 0]
    z = input_obj[1, 1]
    
    return (w*x + x*y*z + 3*w + z*np.power(y,2))

input = np.array([ [1.0, 2.0], [3.0, 4.0] ])

numerical_derivative(func1, input)

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 0) , x[idx] =  1.0
debug 4. grad[idx] =  5.000000000023874
debug 5. grad =  [[5. 0.]
 [0. 0.]]
debug 3. idx =  (0, 1) , x[idx] =  2.0
debug 4. grad[idx] =  13.00000000000523
debug 5. grad =  [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx =  (1, 0) , x[idx] =  3.0
debug 4. grad[idx] =  32.00000000006753
debug 5. grad =  [[ 5. 13.]
 [32.  0.]]
debug 3. idx =  (1, 1) , x[idx] =  4.0
debug 4. grad[idx] =  15.000000000000568
debug 5. grad =  [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])